"""unique togather

Revision ID: 15ec4bdfa423
Revises: 9ec1e7b9b68b
Create Date: 2023-10-23 17:29:43.843656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ec4bdfa423'
down_revision: Union[str, None] = '9ec1e7b9b68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_roles', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='unique')
    # ### end Alembic commands ###
