"""remove full name column from User model

Revision ID: 27caf59fc680
Revises: ac7f128c143e
Create Date: 2023-10-20 11:39:57.154531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27caf59fc680'
down_revision: Union[str, None] = 'ac7f128c143e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
