"""change UserRole description

Revision ID: 4150fe9043e8
Revises: db46851a621d
Create Date: 2023-10-23 17:08:57.600174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4150fe9043e8'
down_revision: Union[str, None] = 'db46851a621d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('description', sa.String(length=250), nullable=True))
    op.drop_column('user_roles', 'descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('descriptions', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('user_roles', 'description')
    # ### end Alembic commands ###
