"""change UserRole to changes

Revision ID: 4cad75766a20
Revises: ffb5e72f9a75
Create Date: 2023-10-20 13:03:39.032466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cad75766a20'
down_revision: Union[str, None] = 'ffb5e72f9a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_roles_name2_key', 'user_roles', type_='unique')
    op.drop_column('user_roles', 'name2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('name2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_roles_name2_key', 'user_roles', ['name2'])
    # ### end Alembic commands ###
