"""somechanges for foregn keys

Revision ID: 89a73b5537b8
Revises: dd84e7c1e76e
Create Date: 2023-10-23 16:58:42.427670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a73b5537b8'
down_revision: Union[str, None] = 'dd84e7c1e76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
