"""remove role_id

Revision ID: db46851a621d
Revises: 89a73b5537b8
Create Date: 2023-10-23 17:05:45.359138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db46851a621d'
down_revision: Union[str, None] = '89a73b5537b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_role_id_fkey', 'users', 'user_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
