"""remove name unique from UserRole

Revision ID: ec2786a2dab7
Revises: 15ec4bdfa423
Create Date: 2023-10-23 17:31:32.214127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2786a2dab7'
down_revision: Union[str, None] = '15ec4bdfa423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_roles_name_key', 'user_roles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_roles_name_key', 'user_roles', ['name'])
    # ### end Alembic commands ###
