"""change UserRole name2

Revision ID: ffb5e72f9a75
Revises: d9297f79c926
Create Date: 2023-10-20 11:58:26.022981

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from app.utils.choices import UserRoleChoices

# revision identifiers, used by Alembic.
revision: str = 'ffb5e72f9a75'
down_revision: Union[str, None] = 'd9297f79c926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles',
                  sa.Column('name2', sqlalchemy_utils.types.choice.ChoiceType(choices=UserRoleChoices), nullable=True))
    op.create_unique_constraint(None, 'user_roles', ['name2'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_column('user_roles', 'name2')
    # ### end Alembic commands ###
